# Generated by Django 5.0.2 on 2024-02-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_product_review_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Post',
        ),
    ]
