# Generated by Django 5.0.2 on 2024-02-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
